[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install --upgrade pip setuptools wheel", "python -m pip install -r requirements.txt --only-binary=all"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd api && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
